import type { Prospect, Client, FollowUp, Quote, Task } from './types'

function id(prefix: string, n: number) { return `${prefix}_${n}_${Date.now()}` }

function daysAgo(n: number) {
  const d = new Date(); d.setDate(d.getDate() - n); return d.toISOString().split('T')[0]
}
function daysFromNow(n: number) {
  const d = new Date(); d.setDate(d.getDate() + n); return d.toISOString().split('T')[0]
}

export const seedProspects: Prospect[] = [
  { id: id('pros', 1), name: 'Roberto Mendoza', company: 'Constructora del Norte', phone: '8112345678', email: 'roberto@constructoranorte.com', origin: 'Recomendación', type: 'Constructora', interest: 'Porcelanatos y adhesivos', notes: 'Proyecto de 40 casas en Escobedo', status: 'Nuevo', priority: 'Alta', nextAction: 'Primer contacto telefónico', nextActionDate: daysFromNow(0), assignedTo: 'Vendedor Nogalera', createdAt: daysAgo(1), updatedAt: daysAgo(1) },
  { id: id('pros', 2), name: 'Mariana Ibarra', company: 'Arquitectura Integral', phone: '8187654321', email: 'mariana@arquitecturaintegral.mx', origin: 'WhatsApp', type: 'Arquitecto', interest: 'Azulejos y muebles de baño', notes: 'Proyecto de 3 baños en residencial', status: 'Contactado', priority: 'Media', nextAction: 'Enviar catálogo de azulejos', nextActionDate: daysFromNow(2), assignedTo: 'Vendedor Nogalera', createdAt: daysAgo(5), updatedAt: daysAgo(3) },
  { id: id('pros', 3), name: 'Carlos Rivera', company: 'Rivera Instalaciones', phone: '8122334455', email: 'carlos@riverainstala.com', origin: 'Llamada', type: 'Instalador', interest: 'Adhesivos y boquillas', notes: 'Compra recurrente cada 15 días', status: 'Interesado', priority: 'Alta', nextAction: 'Cotizar adhesivo por mayoreo', nextActionDate: daysFromNow(1), assignedTo: 'Vendedor Nogalera', createdAt: daysAgo(10), updatedAt: daysAgo(2) },
  { id: id('pros', 4), name: 'Laura Quintana', company: 'Quintana Diseño', phone: '8199988776', email: 'laura@quintanadiseno.com', origin: 'Visita a tienda', type: 'Arquitecto', interest: 'Pisos de porcelanato', notes: 'Visitó la tienda, quiere muestras', status: 'Cotización enviada', priority: 'Alta', nextAction: 'Dar seguimiento a cotización', nextActionDate: daysAgo(1), assignedTo: 'Vendedor Nogalera', createdAt: daysAgo(12), updatedAt: daysAgo(3) },
  { id: id('pros', 5), name: 'Pedro Gómez', company: 'Gómez Constructores', phone: '8111223344', email: 'pedro@gzconstructores.com', origin: 'Página web', type: 'Constructora', interest: 'Minisplits y boilers', notes: 'Proyecto de 12 departamentos', status: 'Nuevo', priority: 'Media', nextAction: 'Llamar para conocer requerimientos', nextActionDate: daysFromNow(3), assignedTo: 'Vendedor Nogalera', createdAt: daysAgo(2), updatedAt: daysAgo(2) },
  { id: id('pros', 6), name: 'Ana Lucía Treviño', company: 'Treviño Ingeniería', phone: '8188776655', email: 'ana@trevinoingenieria.com', origin: 'Recomendación', type: 'Ingeniero', interest: 'Tinacos y bombas', notes: 'Proyecto de cisterna para edificio', status: 'Seguimiento', priority: 'Media', nextAction: 'Enviar ficha técnica de bombas', nextActionDate: daysFromNow(5), assignedTo: 'Vendedor Nogalera', createdAt: daysAgo(20), updatedAt: daysAgo(7) },
  { id: id('pros', 7), name: 'Esteban Ruiz', company: 'Ruiz Contratista', phone: '8123456000', email: 'esteban@ruizconstruye.com', origin: 'Llamada', type: 'Contratista', interest: 'Grifería para baños', notes: '', status: 'Perdido', priority: 'Baja', nextAction: '', nextActionDate: '', assignedTo: 'Vendedor Nogalera', createdAt: daysAgo(45), updatedAt: daysAgo(30) },
  { id: id('pros', 8), name: 'Sofía Cantú', company: 'Cantú Proyectos', phone: '8188001122', email: 'sofia@cantupyo.com', origin: 'Redes sociales', type: 'Empresa', interest: 'Pisos y recubrimientos', notes: 'Posible proyecto de oficinas', status: 'Archivado', priority: 'Baja', nextAction: '', nextActionDate: '', assignedTo: 'Vendedor Nogalera', createdAt: daysAgo(60), updatedAt: daysAgo(30) },
]

export const seedClients: Client[] = [
  { id: id('cli', 1), name: 'Jorge Martínez', company: 'Martínez Construcciones', phone: '8111112233', email: 'jorge@martinezconstruye.com', rfc: 'MTCJ880101', address: 'Av. Constitución 123', city: 'Monterrey', type: 'Constructora', classification: 'Lista 3', status: 'Activo', priority: 'Crítica', interest: 'Porcelanatos, sanitarios, grifería', notes: 'Cliente estratégico. Compra mensual promedio de $45,000', assignedTo: 'Vendedor Nogalera', createdAt: daysAgo(180), updatedAt: daysAgo(3) },
  { id: id('cli', 2), name: 'Patricia Rangel', company: 'Rangel Arquitectos', phone: '8122223344', email: 'paty@rangelarquitectos.com', rfc: 'RAGP950202', address: 'Calzada del Valle 456', city: 'San Pedro', type: 'Arquitecto', classification: 'Lista 3', status: 'Activo', priority: 'Alta', interest: 'Azulejos, muebles de baño, tarjas', notes: 'Proyectos residenciales de alta gama', assignedTo: 'Vendedor Nogalera', createdAt: daysAgo(120), updatedAt: daysAgo(5) },
  { id: id('cli', 3), name: 'Luis Hinojosa', company: 'Hinojosa Instalaciones', phone: '8133334455', email: 'luis@hinstala.com', rfc: 'HILU870303', address: 'Av. Lincoln 789', city: 'Monterrey', type: 'Instalador', classification: 'Lista 3', status: 'Activo', priority: 'Media', interest: 'Adhesivos, boquillas, herramientas', notes: 'Compra quincenal de adhesivos', assignedTo: 'Vendedor Nogalera', createdAt: daysAgo(90), updatedAt: daysAgo(10) },
  { id: id('cli', 4), name: 'Mónica Garza', company: 'Garza y Asociados', phone: '8144445566', email: 'monica@garzaasociados.com', rfc: 'GAMO900101', address: 'Boulevard Díaz Ordaz 321', city: 'Monterrey', type: 'Ingeniero', classification: 'Lista 3', status: 'Inactivo', priority: 'Media', interest: 'Boilers, tinacos, bombas', notes: 'No compra desde hace 60 días', assignedTo: 'Vendedor Nogalera', createdAt: daysAgo(200), updatedAt: daysAgo(60) },
  { id: id('cli', 5), name: 'Fernando Cavazos', company: 'FerConstruye', phone: '8155556677', email: 'fer@ferconstruye.com', rfc: 'CAFE880505', address: 'Carretera Nacional 1000', city: 'Monterrey', type: 'Contratista', classification: 'Lista 3', status: 'Activo', priority: 'Alta', interest: 'Porcelanatos, adhesivos, grifería', notes: 'Proyecto actual de 20 departamentos', assignedTo: 'Vendedor Nogalera', createdAt: daysAgo(60), updatedAt: daysAgo(2) },
]

export const seedFollowUps: FollowUp[] = [
  { id: id('fu', 1), relatedTo: seedClients[0].id, relatedType: 'client', contactMethod: 'Llamada', date: daysAgo(3), result: 'Cliente solicitó cotización de porcelanato', notes: 'Requiere 200m2 de porcelanato', nextAction: 'Enviar cotización', nextActionDate: daysAgo(1), assignedTo: 'Vendedor Nogalera', status: 'Pendiente', createdAt: daysAgo(3) },
  { id: id('fu', 2), relatedTo: seedClients[1].id, relatedType: 'client', contactMethod: 'WhatsApp', date: daysAgo(5), result: 'Envié catálogo de azulejos', notes: 'Cliente va a revisar y me confirma', nextAction: 'Esperar respuesta y dar seguimiento', nextActionDate: daysFromNow(2), assignedTo: 'Vendedor Nogalera', status: 'Pendiente', createdAt: daysAgo(5) },
  { id: id('fu', 3), relatedTo: seedClients[2].id, relatedType: 'client', contactMethod: 'Visita a tienda', date: daysAgo(10), result: 'Cliente compró adhesivo', notes: 'Compra de 50 bultos', nextAction: 'Llamar para próxima orden', nextActionDate: daysFromNow(5), assignedTo: 'Vendedor Nogalera', status: 'Finalizada', createdAt: daysAgo(10) },
  { id: id('fu', 4), relatedTo: seedProspects[3].id, relatedType: 'prospect', contactMethod: 'Correo', date: daysAgo(3), result: 'Se envió cotización de porcelanato', notes: 'Cotización por 150m2', nextAction: 'Dar seguimiento a cotización', nextActionDate: daysAgo(1), assignedTo: 'Vendedor Nogalera', status: 'Pendiente', createdAt: daysAgo(3) },
  { id: id('fu', 5), relatedTo: seedProspects[1].id, relatedType: 'prospect', contactMethod: 'WhatsApp', date: daysAgo(5), result: 'Cliente interesado en azulejos', notes: 'Pidió información de medidas', nextAction: 'Enviar catálogo', nextActionDate: daysFromNow(2), assignedTo: 'Vendedor Nogalera', status: 'En proceso', createdAt: daysAgo(5) },
  { id: id('fu', 6), relatedTo: seedClients[3].id, relatedType: 'client', contactMethod: 'Llamada', date: daysAgo(60), result: 'No contestó', notes: 'Intentar en otro horario', nextAction: 'Volver a llamar', nextActionDate: daysAgo(55), assignedTo: 'Vendedor Nogalera', status: 'Pendiente', createdAt: daysAgo(60) },
]

export const seedQuotes: Quote[] = [
  { id: id('q', 1), relatedTo: seedClients[0].id, relatedType: 'client', date: daysAgo(3), amount: 85000, status: 'Enviada', notes: '200m2 porcelanato marca X', nextFollowUp: daysAgo(1), assignedTo: 'Vendedor Nogalera', createdAt: daysAgo(3), updatedAt: daysAgo(3) },
  { id: id('q', 2), relatedTo: seedProspects[3].id, relatedType: 'prospect', date: daysAgo(3), amount: 62000, status: 'Enviada', notes: '150m2 porcelanato línea Premium', nextFollowUp: daysAgo(1), assignedTo: 'Vendedor Nogalera', createdAt: daysAgo(3), updatedAt: daysAgo(3) },
  { id: id('q', 3), relatedTo: seedProspects[2].id, relatedType: 'prospect', date: daysAgo(5), amount: 38000, status: 'Pendiente', notes: 'Adhesivo por mayoreo (200 bultos)', nextFollowUp: daysFromNow(1), assignedTo: 'Vendedor Nogalera', createdAt: daysAgo(5), updatedAt: daysAgo(5) },
  { id: id('q', 4), relatedTo: seedClients[4].id, relatedType: 'client', date: daysAgo(15), amount: 120000, status: 'Aceptada', notes: 'Porcelanato y grifería para 20 departamentos', nextFollowUp: daysAgo(10), assignedTo: 'Vendedor Nogalera', createdAt: daysAgo(15), updatedAt: daysAgo(10) },
  { id: id('q', 5), relatedTo: seedClients[0].id, relatedType: 'client', date: daysAgo(45), amount: 95000, status: 'Rechazada', notes: 'Cliente encontró mejor precio', nextFollowUp: '', assignedTo: 'Vendedor Nogalera', createdAt: daysAgo(45), updatedAt: daysAgo(40) },
]

export const seedTasks: Task[] = [
  { id: id('t', 1), title: 'Llamar a Jorge Martínez', description: 'Seguimiento de cotización de porcelanato', relatedTo: seedClients[0].id, relatedType: 'client', date: daysFromNow(0), priority: 'Crítica', status: 'Pendiente', assignedTo: 'Vendedor Nogalera', createdAt: daysAgo(1) },
  { id: id('t', 2), title: 'Enviar catálogo a Mariana Ibarra', description: 'Catálogo de azulejos para proyecto de baños', relatedTo: seedProspects[1].id, relatedType: 'prospect', date: daysFromNow(2), priority: 'Alta', status: 'Pendiente', assignedTo: 'Vendedor Nogalera', createdAt: daysAgo(2) },
  { id: id('t', 3), title: 'Seguimiento cotización Laura Quintana', description: 'Cotización vencida de porcelanato', relatedTo: seedProspects[3].id, relatedType: 'prospect', date: daysAgo(0), priority: 'Alta', status: 'Pendiente', assignedTo: 'Vendedor Nogalera', createdAt: daysAgo(2) },
  { id: id('t', 4), title: 'Cotizar adhesivo para Carlos Rivera', description: 'Precio por mayoreo de adhesivo', relatedTo: seedProspects[2].id, relatedType: 'prospect', date: daysFromNow(1), priority: 'Alta', status: 'Pendiente', assignedTo: 'Vendedor Nogalera', createdAt: daysAgo(1) },
  { id: id('t', 5), title: 'Recuperar a Mónica Garza', description: 'Cliente inactivo 60 días sin comprar', relatedTo: seedClients[3].id, relatedType: 'client', date: daysFromNow(0), priority: 'Media', status: 'Pendiente', assignedTo: 'Vendedor Nogalera', createdAt: daysAgo(3) },
  { id: id('t', 6), title: 'Llamar nuevo prospecto Constructora del Norte', description: 'Prospecto nuevo sin contacto', relatedTo: seedProspects[0].id, relatedType: 'prospect', date: daysFromNow(0), priority: 'Alta', status: 'Pendiente', assignedTo: 'Vendedor Nogalera', createdAt: daysAgo(1) },
]
